### ISSUE TITLE
出现这个报错程序不会尝试重新连接

### ISSUE THREAD

**Issue by Jack-Ywn** [xintai6660707/ore-mine-pool#1]
`thread 'main' panicked at src/worker.rs:99:114:
called Result::unwrap() on an Err value: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(47.254.156.237)), port: Some(7891), path: "/submit_answer", query: None, fragment: None }, source: hyper::Error(Io, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace`

**Comment by xintai6660707** [comment]
好的，下次修复一下。

**Comment by 18701652582** [comment]
windows版本的还是无法运行呢

**Comment by xintai6660707** [comment]
来discord交流吧
