### ISSUE TITLE
Error when difficulty is matching >20+ thread 'main' panicked at src/worker

### ISSUE THREAD

**Issue by ralphacpm** [xintai6660707/ore-mine-pool#2]
[2m2024-08-14T07:49:30.091935Z[0m [32m INFO[0m [2more_mine_pool::worker[0m[2m:[0m Best hash: 1119djubgdraRoinEtaouUs992FvuMu7zWGqXDXaWXZ (difficulty: 24)
thread 'main' panicked at src/worker.rs:125:66:
called `Result::unwrap()` on an `Err` value: WrongSize
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2m2024-08-14T07:49:39.211117Z[0m [32m INFO[0m [2more_mine_pool::worker[0m[2m:[0m server_url_list: ["http://47.254.156.237:7891/", "http://8.211.40.189:7891/", "http://8.211.56.185:7891/", "http://8.211.49.103:7891/", "http://8.211.52.3:7891/", "http://8.209.80.175:7891/", "http://8.211.53.52:7891/"]

**Comment by xintai6660707** [comment]
After we were attacked by ddos, we changed the route server address ，you can used the new command to execute

**Comment by xintai6660707** [comment]
Let me add some retry
